create table company (id bigint generated by default as identity, model varchar(255), owner_id bigint, parking_id bigint, primary key (id))
create table address (id bigint generated by default as identity, name varchar(255), primary key (id))
create table city_parkings (city_id bigint not null, parkings_id bigint not null)
create table city_people (city_id bigint not null, people_id bigint not null)
create table parking (id bigint generated by default as identity, address varchar(255), city_id bigint, primary key (id))
create table parking_cars (parking_id bigint not null, cars_id bigint not null)
create table parking_clients (parking_lots_id bigint not null, clients_id bigint not null)
create table passport (id bigint generated by default as identity, number varchar(255), series varchar(255), owner_id bigint, primary key (id))
create table person (id bigint generated by default as identity, age integer, first_name varchar(255), last_name varchar(255), city_id bigint, passport_id bigint, primary key (id))
alter table city_parkings drop constraint if exists UK_a7qmb5yasegveofj6fjloc2o4
alter table city_parkings add constraint UK_a7qmb5yasegveofj6fjloc2o4 unique (parkings_id)
alter table city_people drop constraint if exists UK_p89p3d2itq99gva2yowpfm92d
alter table city_people add constraint UK_p89p3d2itq99gva2yowpfm92d unique (people_id)
alter table parking_cars drop constraint if exists UK_t009aheqex998iisfwutqft6s
alter table parking_cars add constraint UK_t009aheqex998iisfwutqft6s unique (cars_id)
alter table company add constraint FKgbiqmhhk4njnmkkerl1lvqppk foreign key (owner_id) references person
alter table company add constraint FK7518bwte0cpq77k559otxa6uq foreign key (parking_id) references parking
alter table city_parkings add constraint FKjvyaak9knpcpko6724bechm2a foreign key (parkings_id) references parking
alter table city_parkings add constraint FKgenmgoidy2ud3phyesf5q1ixr foreign key (city_id) references address
alter table city_people add constraint FKfpegww2uill61270w0m3i0t3e foreign key (people_id) references person
alter table city_people add constraint FKaoovh075beqm2ikim3pkwqydq foreign key (city_id) references address
alter table parking add constraint FKn87sbnjc8t0nvo2tk3h19iavp foreign key (city_id) references address
alter table parking_cars add constraint FKjoht5qwxq95s4m9ct1nfdiess foreign key (cars_id) references company
alter table parking_cars add constraint FKfoaby9e3ikyy7hq5imjrj9mr5 foreign key (parking_id) references parking
alter table parking_clients add constraint FKeiqstl3bv71wubkp8sii9bl88 foreign key (clients_id) references person
alter table parking_clients add constraint FKdtnt0q0f9ekyxy1lvnx0qmc9b foreign key (parking_lots_id) references parking
alter table passport add constraint FKgq5rwi11mexsgy6ei617if01p foreign key (owner_id) references person
alter table person add constraint FK4vi48j2by4qpm7v93r3vulf1e foreign key (city_id) references address
alter table person add constraint FKpm70pbnghc1m7eq6n4jf5fkd foreign key (passport_id) references passport